import assert from "node:assert/strict";
import test from "node:test";
import { AnalyzeInputSchema, CloudErrorCodeSchema, CloudMutationSchema, SyncMetadataSchema, SyncPushRequestSchema } from "@wisdom/shared";
import { conflictDuplicateId, stableHash, SYNC_BATCH_SIZE } from "./cloud/sync";
import { claimsAreAdmin, claimsUserId } from "./supabase/claims";
import { adminAuthorization } from "./admin/authorization";
import { canEdit, canTransition } from "./admin/contentTransitions";
import { safeAuditMetadata } from "./admin/safeAuditMetadata";
import { batches, summarizeResults } from "./sync/batchProcessor";
import { planSync } from "./sync/syncPlanner";
import { resolveConflict } from "./sync/conflictResolver";
import { migrationProgress } from "./sync/migrationRunner";

test("cloud error code 維持封閉集合", () => assert.equal(CloudErrorCodeSchema.safeParse("CLOUD_INTERNAL_ERROR").success, true));
test("未知 cloud error code 被拒絕", () => assert.equal(CloudErrorCodeSchema.safeParse("SQL_ERROR").success, false));
test("cloud mutation 不接受無 payload", () => assert.equal(CloudMutationSchema.safeParse({}).success, false));
test("cloud mutation 不接受負 revision", () => assert.equal(CloudMutationSchema.safeParse({ payload: {}, expectedRevision: -1 }).success, false));
test("claims 接受 subject", () => assert.equal(claimsUserId({ sub: "user-1" }), "user-1"));
test("claims 拒絕缺少 subject", () => assert.equal(claimsUserId({}), null));
test("user metadata admin 不授權", () => assert.equal(claimsAreAdmin({ app_metadata: {}, user_metadata: { role: "admin" } } as never), false));
test("app metadata admin 授權", () => assert.equal(claimsAreAdmin({ app_metadata: { role: "admin" } }), true));
test("app metadata 非 admin 拒絕", () => assert.equal(claimsAreAdmin({ app_metadata: { role: "editor" } }), false));
test("stable hash 固定 64 hex", async () => assert.match(await stableHash({ a: 1 }), /^[a-f0-9]{64}$/));
test("stable hash 相同輸入相同", async () => assert.equal(await stableHash({ a: 1 }), await stableHash({ a: 1 })));
test("stable hash 不同輸入不同", async () => assert.notEqual(await stableHash({ a: 1 }), await stableHash({ a: 2 })));
test("duplicate id 保留來源識別", () => assert.match(conflictDuplicateId("report-a"), /^report-a-copy-/));
test("sync batch size 固定 25", () => assert.equal(SYNC_BATCH_SIZE, 25));
test("sync push 最多 25 entities", () => { const entities = Array.from({ length: 26 }, (_, index) => ({ entityType: "report" as const, entityId: String(index), payload: {}, hash: "a".repeat(64) })); assert.equal(SyncPushRequestSchema.safeParse({ deviceId: "d", entities }).success, false); });
test("sync metadata 接受 local_only", () => assert.equal(SyncMetadataSchema.safeParse({ entityId: "r", localUpdatedAt: new Date().toISOString(), cloudRevision: null, lastSyncedHash: null, lastSyncedAt: null, syncState: "local_only", source: "local", pendingOperation: "none" }).success, true));
for (const state of ["pending_upload", "pending_download", "syncing", "synced", "conflict", "offline", "error"] as const) test(`sync metadata 支援 ${state}`, () => assert.equal(SyncMetadataSchema.safeParse({ entityId: state, localUpdatedAt: new Date().toISOString(), cloudRevision: null, lastSyncedHash: null, lastSyncedAt: null, syncState: state, source: "local", pendingOperation: "none" }).success, true));
for (const operation of ["create", "update", "delete", "none"] as const) test(`sync metadata 支援 ${operation}`, () => assert.equal(SyncMetadataSchema.safeParse({ entityId: operation, localUpdatedAt: new Date().toISOString(), cloudRevision: null, lastSyncedHash: null, lastSyncedAt: null, syncState: "local_only", source: "local", pendingOperation: operation }).success, true));
for (const mode of ["auto", "local", "remote"] as const) test(`既有分析模式 ${mode} 可解析`, () => assert.equal(AnalyzeInputSchema.safeParse({ question: "測試", analysisMode: mode }).success, true));
for (const invalid of ["", " ", "x".repeat(2001)]) test("無效決策問題拒絕", () => assert.equal(AnalyzeInputSchema.safeParse({ question: invalid }).success, false));
for (const code of ["CLOUD_NOT_CONFIGURED", "AUTH_REQUIRED", "CLOUD_FORBIDDEN", "CLOUD_INVALID_INPUT", "CLOUD_NOT_FOUND", "CLOUD_CONFLICT", "CLOUD_RATE_LIMITED", "CLOUD_TEMPORARILY_UNAVAILABLE"] as const) test(`安全 API code ${code}`, () => assert.equal(CloudErrorCodeSchema.safeParse(code).success, true));
for (const source of ["local", "cloud", "both"] as const) test(`sync metadata 來源 ${source}`, () => assert.equal(SyncMetadataSchema.safeParse({ entityId: source, localUpdatedAt: new Date().toISOString(), cloudRevision: null, lastSyncedHash: null, lastSyncedAt: null, syncState: "synced", source, pendingOperation: "none" }).success, true));
for (const invalidState of ["uploaded", "waiting", "deleted", ""] as const) test(`未知 sync state ${invalidState || "empty"} 被拒絕`, () => assert.equal(SyncMetadataSchema.safeParse({ entityId: "x", localUpdatedAt: new Date().toISOString(), cloudRevision: null, lastSyncedHash: null, lastSyncedAt: null, syncState: invalidState, source: "local", pendingOperation: "none" }).success, false));
for (const field of ["title", "background", "goal", "resources", "constraints", "risks"] as const) test(`${field} 超長輸入拒絕`, () => { const value = "x".repeat(field === "title" ? 81 : field === "goal" ? 1001 : field === "background" ? 4001 : 2001); assert.equal(AnalyzeInputSchema.safeParse({ question: "ok", [field]: value }).success, false); });
test("metadata 要求 ISO 時間", () => assert.equal(SyncMetadataSchema.safeParse({ entityId: "x", localUpdatedAt: "today", cloudRevision: null, lastSyncedHash: null, lastSyncedAt: null, syncState: "synced", source: "local", pendingOperation: "none" }).success, false));
test("metadata 拒絕非 sha256 hash", () => assert.equal(SyncMetadataSchema.safeParse({ entityId: "x", localUpdatedAt: new Date().toISOString(), cloudRevision: null, lastSyncedHash: "hash", lastSyncedAt: null, syncState: "synced", source: "local", pendingOperation: "none" }).success, false));
test("metadata 不接受 revision zero", () => assert.equal(SyncMetadataSchema.safeParse({ entityId: "x", localUpdatedAt: new Date().toISOString(), cloudRevision: 0, lastSyncedHash: null, lastSyncedAt: null, syncState: "synced", source: "local", pendingOperation: "none" }).success, false));
test("metadata 可紀錄 duplicatedFrom", () => assert.equal(SyncMetadataSchema.safeParse({ entityId: "copy", localUpdatedAt: new Date().toISOString(), cloudRevision: null, lastSyncedHash: null, lastSyncedAt: null, syncState: "pending_upload", source: "both", pendingOperation: "create", duplicatedFrom: "original" }).success, true));
test("cloud mutation 可包含 deviceId", () => assert.equal(CloudMutationSchema.safeParse({ payload: {}, deviceId: "browser-1" }).success, true));
test("cloud mutation 不接受過長 deviceId", () => assert.equal(CloudMutationSchema.safeParse({ payload: {}, deviceId: "x".repeat(201) }).success, false));
test("admin authorization 需要 app metadata", () => assert.equal(adminAuthorization({ sub: "u", app_metadata: { role: "admin" } }).admin, true));
test("admin authorization 拒絕 user metadata", () => assert.equal(adminAuthorization({ sub: "u", app_metadata: {}, user_metadata: { role: "admin" } } as never).admin, false));
for (const [from, to, allowed] of [["draft","reviewed",true],["draft","published",false],["reviewed","published",true],["reviewed","draft",true],["published","archived",true],["published","draft",false],["archived","draft",true],["archived","published",false]] as const) test(`內容轉換 ${from}→${to}`, () => assert.equal(canTransition(from, to), allowed));
test("draft 可編輯", () => assert.equal(canEdit("draft"), true));
test("published 不可直接編輯", () => assert.equal(canEdit("published"), false));
test("audit allowlist 過濾秘密欄位", () => assert.deepEqual(safeAuditMetadata({ changedFields: ["title"], token: "no", payload: "no", version: 2 }), { changedFields: ["title"], version: 2 }));
test("audit 非物件輸出空物件", () => assert.deepEqual(safeAuditMetadata("unsafe"), {}));
test("26 個項目分成 25 加 1", () => assert.deepEqual(batches(Array.from({ length: 26 }, (_, index) => index)).map((item) => item.length), [25, 1]));
test("partial result 可計算 retry", () => assert.equal(summarizeResults([{ entityType: "report", entityId: "1", success: true, operation: "upload", cloudRevision: 1, errorCode: null }, { entityType: "report", entityId: "2", success: false, operation: "upload", cloudRevision: null, errorCode: "CLOUD_TEMPORARILY_UNAVAILABLE" }]).retry.length, 1));
const base = { entityType: "report" as const, entityId: "a", localRevision: 1, cloudRevision: null, localHash: "a", cloudHash: null, state: "local_only" };
test("sync plan 建立 upload", () => assert.equal(planSync([base], [])[0].operation, "upload_create"));
test("sync plan 建立 download", () => assert.equal(planSync([], [{ ...base, cloudRevision: 1, cloudHash: "a" }])[0].operation, "download_create"));
test("sync plan hash 相同 noop", () => assert.equal(planSync([{ ...base, localHash: "x" }], [{ ...base, cloudRevision: 1, cloudHash: "x" }])[0].operation, "noop"));
test("sync plan 相同 revision 不同 hash conflict", () => assert.equal(planSync([{ ...base, localRevision: 1, localHash: "x" }], [{ ...base, cloudRevision: 1, cloudHash: "y" }])[0].operation, "conflict"));
test("keep local 保留 expected revision 行為", () => assert.equal(resolveConflict({ reportId: "r" }, "local").action, "update_with_expected_revision"));
test("keep cloud 建立 backup", () => assert.equal(resolveConflict({ reportId: "r" }, "cloud").action, "backup_then_replace"));
test("keep both 產生新 ID", () => assert.notEqual((resolveConflict({ reportId: "r" }, "both") as { value: { reportId: string } }).value.reportId, "r"));
test("decide later 保留 conflict", () => assert.equal(resolveConflict({ reportId: "r" }, "later").action, "keep_conflict"));
test("migration 26 筆兩批", () => assert.equal(migrationProgress(Array.from({ length: 26 }, (_, index) => String(index))).totalBatches, 2));
